# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Empty matrix test

on:
  workflow_dispatch:

jobs:
  create-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.create-matrix.output.matrix }}
    steps:
      - id: create-matrix
        run: |
          echo matrix='{ "include": [] }' >> $GITHUT_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: create-matrix
    strategy:
      fail-fast: true
      matrix: ${{ fromJson(needs.create-matrix.outputs.matrix) }}
    steps:
      - run: |
          echo hi
  dependency:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: |
          echo run after empty matrix
  
