# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Empty matrix test

on:
  workflow_dispatch:

jobs:
  create-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.create-matrix.outputs.matrix }}
    steps:
      - id: create-matrix
        run: |
          # echo matrix='{ "include": [] }' >> $GITHUB_OUTPUT
          echo hi

  build:
    runs-on: ubuntu-latest
    needs: create-matrix
    if: needs.create-matrix.outputs.matrix
    strategy:
      fail-fast: true
      matrix: ${{ fromJson(needs.create-matrix.outputs.matrix) }}
    steps:
      - run: |
          echo hi
  dependency:
    runs-on: ubuntu-latest
    needs: build
    if: always() && (needs.build.result == 'skipped' || needs.build.result == 'success')
    steps:
      - run: |
          echo run after empty matrix
  
