# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix: ${{ fromJson('[]') }}
    steps:
      - run: |
          echo hi
  dependency:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: |
          echo run after empty matrix
  
