name: Test subworkflow

on:
  workflow_call:
    inputs:
      run-second-job:
        type: boolean
        required: false
        default: false

jobs:
  
  sub-1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [ "1" == "$ATTEMPT" ] ; then
            echo it will fail on first attempt
            exit 1
          fi

          echo job completed

        env:
          ATTEMPT: ${{ github.run_attempt }}
      
  sub-2:
    if: inputs.run-second-job
    runs-on: ubuntu-latest
    steps:
      - run: echo job 2